language: objective-c
branches:
  only:
  - master
notifications:
  email: false
  
before_install: gem install cocoapods

script: 
  - pod install
  - xcodebuild -workspace InPlaceEdit.xcworkspace -scheme InPlaceEditTests -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch 64-bit)' test


